In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import io
%matplotlib inline

In [3]:
def combine_files(target_directory, output_file_name=None, file_ext=None):
    # Get the list of files in the target_directory, sorted by part number
    files = sorted(
        [
            os.path.join(target_directory, f)
            for f in os.listdir(target_directory)
            if os.path.isfile(os.path.join(target_directory, f))
        ]
    )

    if not files:
        print(f"No files found in target_directory {target_directory}")
        return

    combined_data = b""  # Store the combined data as bytes

    # Combine all files into the combined_data variable
    for file in files:
        with open(file, "rb") as f:
            combined_data += f.read()
        print(f"Added {file}")

    # If output_file_name is provided, save to file
    if output_file_name:
        output_file = f"{output_file_name}{file_ext}"
        with open(output_file, "wb") as output:
            output.write(combined_data)
        print(f"Combined all files into {output_file}")

    return combined_data


loan_data_2007_2014 = combine_files(
    "output_chunks", file_ext=".csv"
)

Added output_chunks\loan_data_2007_2014_part_0
Added output_chunks\loan_data_2007_2014_part_1
Added output_chunks\loan_data_2007_2014_part_2

In [4]:
csv_data = io.StringIO(loan_data_2007_2014.decode('utf-8'))

In [5]:
df = pd.read_csv(csv_data, index_col=0, low_memory=False)
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,B2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,C4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,C5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,C1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,B5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df = df.dropna(thresh=len(df)*0.95, axis=1)

In [7]:
df.shape

(466285, 48)

In [8]:
df.head(2)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,last_credit_pull_d,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq
0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,B2,...,0.0,0.00,0.00,Jan-15,171.62,Jan-16,0.0,1,INDIVIDUAL,0.0
1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,C4,...,0.0,117.08,1.11,Apr-13,119.66,Sep-13,0.0,1,INDIVIDUAL,0.0

In [9]:
selected_features = ["int_rate", "installment", "emp_length", "annual_inc", "loan_status", "dti", "delinq_2yrs", "inq_last_6mths", "open_acc", "revol_util", "total_rec_late_fee", "collection_recovery_fee", "last_pymnt_amnt", "collections_12_mths_ex_med"]

In [10]:
selected_df = df[selected_features]
selected_df.head(2)

,int_rate,installment,emp_length,annual_inc,loan_status,dti,delinq_2yrs,inq_last_6mths,open_acc,revol_util,total_rec_late_fee,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med
0,10.65,162.87,10+ years,24000.0,Fully Paid,27.65,0.0,1.0,3.0,83.7,0.0,0.00,171.62,0.0
1,15.27,59.83,< 1 year,30000.0,Charged Off,1.00,0.0,5.0,3.0,9.4,0.0,1.11,119.66,0.0

In [11]:
selected_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 466285 entries, 0 to 466284
Data columns (total 14 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   int_rate                    466285 non-null  float64
 1   installment                 466285 non-null  float64
 2   emp_length                  445277 non-null  object
 3   annual_inc                  466281 non-null  float64
 4   loan_status                 466285 non-null  object
 5   dti                         466285 non-null  float64
 6   delinq_2yrs                 466256 non-null  float64
 7   inq_last_6mths              466256 non-null  float64
 8   open_acc                    466256 non-null  float64
 9   revol_util                  465945 non-null  float64
 10  total_rec_late_fee          466285 non-null  float64
 11  collection_recovery_fee     466285 non-null  float64
 12  last_pymnt_amnt             466285 non-null  float64
 13  collections_12_mths_ex_med  466140 non-null  float64
dtypes: float64(12), object(2)
memory usage: 53.4+ MB

In [12]:
copy_df = selected_df.copy()
for column in copy_df.columns:
    mode_value = copy_df[column].mode().iloc[0]
    copy_df[column].fillna(mode_value, inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_17392\2070804714.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  copy_df[column].fillna(mode_value, inplace=True)

In [13]:
copy_df.head()

,int_rate,installment,emp_length,annual_inc,loan_status,dti,delinq_2yrs,inq_last_6mths,open_acc,revol_util,total_rec_late_fee,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med
0,10.65,162.87,10+ years,24000.0,Fully Paid,27.65,0.0,1.0,3.0,83.7,0.00,0.00,171.62,0.0
1,15.27,59.83,< 1 year,30000.0,Charged Off,1.00,0.0,5.0,3.0,9.4,0.00,1.11,119.66,0.0
2,15.96,84.33,10+ years,12252.0,Fully Paid,8.72,0.0,2.0,2.0,98.5,0.00,0.00,649.91,0.0
3,13.49,339.31,10+ years,49200.0,Fully Paid,20.00,0.0,1.0,10.0,21.0,16.97,0.00,357.48,0.0
4,12.69,67.79,1 year,80000.0,Current,17.94,0.0,0.0,15.0,53.9,0.00,0.00,67.79,0.0

In [14]:
copy_df['emp_length'].value_counts()

emp_length
10+ years    171057
2 years       41373
3 years       36596
< 1 year      36265
5 years       30774
1 year        29622
4 years       28023
7 years       26180
6 years       26112
8 years       22395
9 years       17888
Name: count, dtype: int64

In [15]:
copy_df['loan_status'].value_counts()

loan_status
Current                                                224226
Fully Paid                                             184739
Charged Off                                             42475
Late (31-120 days)                                       6900
In Grace Period                                          3146
Does not meet the credit policy. Status:Fully Paid       1988
Late (16-30 days)                                        1218
Default                                                   832
Does not meet the credit policy. Status:Charged Off       761
Name: count, dtype: int64

In [16]:
mapping = {"10+ years": 10, "9 years": 9, "8 years": 8, "7 years": 7, "6 years": 6, "5 years": 5, "4 years": 4, "3 years": 3, "2 years": 2, "1 year": 1, "< 1 year": 0}
copy_df = copy_df.replace({'emp_length': mapping})
copy_df.head(2)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_17392\1793892073.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  copy_df = copy_df.replace({'emp_length': mapping})

,int_rate,installment,emp_length,annual_inc,loan_status,dti,delinq_2yrs,inq_last_6mths,open_acc,revol_util,total_rec_late_fee,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med
0,10.65,162.87,10,24000.0,Fully Paid,27.65,0.0,1.0,3.0,83.7,0.0,0.00,171.62,0.0
1,15.27,59.83,0,30000.0,Charged Off,1.00,0.0,5.0,3.0,9.4,0.0,1.11,119.66,0.0

In [17]:
mapping = {
    'Fully Paid': 1,
    'Charged Off': 0,
    'Current': 1,
    'Default': 0,
    'Late (31-120 days)': 0,
    'In Grace Period': 0,
    'Late (16-30 days)': 0,
    'Does not meet the credit policy. Status:Fully Paid': 1,
    'Does not meet the credit policy. Status:Charged Off': 0
}
copy_df = copy_df.replace({'loan_status': mapping})
copy_df.head(2)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_17392\2899368823.py:12: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  copy_df = copy_df.replace({'loan_status': mapping})

,int_rate,installment,emp_length,annual_inc,loan_status,dti,delinq_2yrs,inq_last_6mths,open_acc,revol_util,total_rec_late_fee,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med
0,10.65,162.87,10,24000.0,1,27.65,0.0,1.0,3.0,83.7,0.0,0.00,171.62,0.0
1,15.27,59.83,0,30000.0,0,1.00,0.0,5.0,3.0,9.4,0.0,1.11,119.66,0.0

In [18]:
X = copy_df.drop('loan_status', axis=1)
y = copy_df['loan_status']

In [19]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

In [21]:
from sklearn.ensemble import GradientBoostingClassifier

clf = GradientBoostingClassifier()
clf.fit(X_train, y_train)

GradientBoostingClassifier()

In [22]:
y_pred = clf.predict(X_test)

In [23]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      0.44      0.61     16739
           1       0.93      1.00      0.96    123147

    accuracy                           0.93    139886
   macro avg       0.95      0.72      0.78    139886
weighted avg       0.93      0.93      0.92    139886